myapplication:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local,qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      address: http://localhost:8080/xxx/

    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://s3-cn-north-1.qiniucs.com
      accessKey: b9E8KElL6je8XJKEjK_GEj8BY-fAogcB0-uN2C8r
      secretKey: 6oF4MJmWx4NgoSJ36KK6jpey347MMrmmR_OCpnv4
      bucketName: pengcloud01

# 阿里云对象存储配置信息
#    aliyun:
#      endpoint: oss-cn-shenzhen.aliyuncs.com
#      accessKeyId: 111111
#      accessKeySecret: xxxxxx
#      bucketName: litemall
#    # 腾讯对象存储配置信息
#    # 请参考 https://cloud.tencent.com/document/product/436/6249
#    tencent:
#      secretId: AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
#      secretKey: XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
#      region: ap-shanghai
#      bucketName: vytech-1300096589